### ISSUE TITLE
Spigot 1.9.4 incompatibility - plugin will not start

### ISSUE THREAD

**Issue by tmad40blue** [ShepherdJerred/stServerMessages#2]
Hi, looks like stServerMessages will not enable under Spigot 1.9.4:

```
[15:57:16] [Server thread/ERROR]: Error occurred while enabling stServerMessages v1.5.5 (Is it up to date?)                                                
java.lang.NoClassDefFoundError: net/minecraft/server/v1_9_R1/Packet                                                                                        
        at com.shepherdjerred.stservermessages.Main.onEnable(Main.java:46) ~[stServerMessages.jar:?]                                                       
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot.jar:git-Spigot-8a048fe-a022dd2]                                      
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-8a048fe-a022dd2]                         
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-8a048fe-a022dd2]                        
        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:362) [spigot.jar:git-Spigot-8a048fe-a022dd2]                             
        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:322) [spigot.jar:git-Spigot-8a048fe-a022dd2]                          
        at net.minecraft.server.v1_9_R2.MinecraftServer.t(MinecraftServer.java:416) [spigot.jar:git-Spigot-8a048fe-a022dd2]                                
        at net.minecraft.server.v1_9_R2.MinecraftServer.l(MinecraftServer.java:381) [spigot.jar:git-Spigot-8a048fe-a022dd2]                                
        at net.minecraft.server.v1_9_R2.MinecraftServer.a(MinecraftServer.java:336) [spigot.jar:git-Spigot-8a048fe-a022dd2]                                
        at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:268) [spigot.jar:git-Spigot-8a048fe-a022dd2]                             
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) [spigot.jar:git-Spigot-8a048fe-a022dd2]                              
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]                                                                                              
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_9_R1.Packet                                                                           
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-8a048fe-a022dd2]                          
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-8a048fe-a022dd2]                          
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_66]                                                                             
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_66]                                                                             
        ... 12 more  
```

**Comment by ShepherdJerred** [comment]
I'll look into it when I get home in one and a half weeks.

**Comment by ShepherdJerred** [comment]
Updated to 1.10 with latest release
